# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReceiptsClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Money'
  pod 'SwiftyJSON'

  # Pods for ReceiptsClient

end
